#couchbase Configuration
couchbase.nodes: "localhost"
couchbase.bucket: "Products"
couchbase.password : "password"

database:
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: root
    url: jdbc:mysql://localhost/dropwizard

template: "healthcheck-%s"